### ISSUE TITLE
为什么加载的页面先显示带themeleaf的标签，然后加载完才显示数据？求教

### ISSUE THREAD

**Issue by caglee** [wzypandaking/rbac-shiro#2]

**Comment by wzypandaking** [comment]
因为我也是第一次用，没有遇到你说的那种情况，我也不太清楚。
但我觉得，themeleaf是作为一个模板引擎，正常情况下，会在服务端解析完成后再返回给前端的。

**Comment by wzypandaking** [comment]
我又仔细的看了一下这个问题，发现展示不是themeleaf错。
是我是用了一个前端的模板引擎`ArtTemplate`，没有对这些模板进行隐藏。
对于这个问题你可以将 tbody#data-list 里边的内容放入`<script type="text/html" id='tpl'></script>`中;修改`loadArtTemplate('data-list');`为`loadArtTemplate('tpl');` 。这样问题就可以解决。
